package com.imooc.two.dubbo.module.mapper;

import com.imooc.two.dubbo.module.entity.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    int insertSelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated Sat Jun 01 21:27:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(PayInfo record);
}